/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 05-30-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class SnowFlakeResponse
{
    public String patientId{get;set;}
    public String totalUnits{get;set;}
    public String procedureCodeDesc{get;set;}   
    public String PROVIDERID{get;set;} 
    public String chargeId{get;set;} 
}